### ISSUE TITLE
[BUG] TypeErro do módulo ao rodar cron.php manualmente

### ISSUE THREAD

**Issue by brunoferreiralkn** [nfe/whmcs-addon#151]
**Descreva o erro**
TypeErro do módulo ao rodar cron.php manualmente.

**Como reproduzir**
Etapas para reproduzir o comportamento:
Rodar o arquivo cron.php manualmente `php -q /path/to/cron.php all`

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

**Screenshots**
![image](https://github.com/nfe/whmcs-addon/assets/84975603/109ca11b-2b0b-4c36-bffc-e44dc97fe8e8)

![image](https://github.com/nfe/whmcs-addon/assets/84975603/c14243d3-155e-48a3-b5cd-8468931b532e)

Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

**Ambiente e versões:**
- Versão do módulo: 2.1.8
- Versão do WHMCS: 8.7
- Versão do PHP: 8.1

**Comment by feperrella** [comment]
Hi, same issue here:

```
TypeError: Cannot access offset of type string on string in /modules/addons/NFEioServiceInvoices/lib/NFEio/Nfe.php:337

#0 /modules/addons/NFEioServiceInvoices/lib/Hooks/AfterCronJob.php(68): NFEioServiceInvoices\NFEio\Nfe->emit(Object(stdClass))
#1 /modules/addons/NFEioServiceInvoices/hooks.php(69): NFEioServiceInvoices\Hooks\AfterCronJob->run()
#2 [internal function]: WHMCS\Utility\SafeInclude::{closure}(Array)
#3 /vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php(0): call_user_func(Object(Closure), Array)
#4 /vendor/illuminate/support/Facades/Facade.php(261): WHMCS\Hook\Manager->run('AfterCronJob', Array, false)
#5 /includes/functions.php(0): Illuminate\Support\Facades\Facade::__callStatic('run', Array)
#6 /vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): run_hook('AfterCronJob', Array)
#7 /vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->tearDown()
#8 /vendor/symfony/console/Command/Command.php(298): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /vendor/symfony/console/Application.php(1028): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\AllCommand), Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home2/fapnet/whmcsdata/crons/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
