### ISSUE TITLE
[BUG] Erro ao atualizar na tela configuração

### ISSUE THREAD

**Issue by andercrist** [nfe/whmcs-addon#162]
Atualizei o Módulo da versão 2.1.8 para a 2.2.0 e ao clicar em Configuração retorna erro:
2024/08/15 11:02:24 [error] 1397#0: *157887 FastCGI sent in stderr: "PHP message: [WHMCS Application] ERROR: Error: Call to a member function getAttributes() on array in /www/wwwroot/compilare.com.br/modules/addons/NFEioServiceInvoices/lib/NFEio/Nfe.php:88 Stack trace: #0 /www/wwwroot/compilare.com.br/modules/addons/NFEioServiceInvoices/lib/NFEio/Nfe.php(57): NFEioServiceInvoices\NFEio\Nfe->getCompanies() #1 /www/wwwroot/compilare.com.br/modules/addons/NFEioServiceInvoices/lib/Admin/Controller.php(88): NFEioServiceInvoices\NFEio\Nfe->companiesDropDownValues() #2 /www/wwwroot/compilare.com.br/modules/addons/NFEioServiceInvoices/lib/Admin/AdminDispatcher.php(29): NFEioServiceInvoices\Admin\Controller->configuration() #3 /www/wwwroot/compilare.com.br/modules/addons/NFEioServiceInvoices/NFEioServiceInvoices.php(144): NFEioServiceInvoices\Admin\AdminDispatcher->dispatch() #4 /www/wwwroot/compilare.com.br/XXXX/addonmodules.php(0): NFEioServiceInvoices_output() #5 {main} {"exception":"[object] (Error(code: 0): Call to a member function getAttributes() on" while reading response header from upstream, client: 179.130.90.158, server: compilare.com.br, request: "GET /XXXX/addonmodules.php?module=NFEioServiceInvoices&action=configuration HTTP/2.0", upstream: "fastcgi://unix:/tmp/php-cgi-74.sock:", host: "compilare.com.br", referrer: "https://compilare.com.br/XXXX/addonmodules.php?module=NFEioServiceInvoices&action=about"

**Ambiente e versões:**
- Versão do módulo: 2.2.0
- Versão do WHMCS: 8.5.1
- Versão do PHP: 7.4

**Comment by andercrist** [comment]
Descobri o problema, era uma fatura que não tinha sido paga e por isso eles cortaram o acesso e não notificaram a gente.
